const Languages = {
  en: {
    //common Strings
    sideBarMain: 'MAIN',
    from: 'from',
    to: 'to',
    done: 'Done',
    skip: 'Skip',
    next: 'Next',
    cash: 'Cash',
    online: 'Online',
    loginForOrder: 'PLEASE LOGIN TO CONTINUE YOUR ORDER',
    verificationTitle: 'PLEASE INSERT VERIFICATION CODE',
    verificationNumber: 'Verification code send to',
    verificationCode: 'VERIFICATION CODE',
    codeResend: 'Resend code in Seconds',
    loginSuccessText: 'Login successfully, please complete your order',
    cancel: 'Cancel',
    mainPage: 'Main Page',
    orderHistory: 'Order History',
    myOrder: 'MY ORDERS',
    accountSetting: 'ACCOUNT SETTINGS',
    accountSetting2: 'ACCOUNT SETTINGS',
    registerAsProvider: 'REGISTER AS PROVIDER',
    faqText: 'FAQs',
    aboutUs: 'ABOUT US',
    signOut: 'SIGN OUT',
    shareApp: 'SHARE THE APP',
    save: 'SAVE',
    aboutUsText: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. ',
    text: 'Why using Back application?',
    weakPassword: 'WEAK PASSWORD',
    strongPasssword: 'STRONG PASSWORD',
    send: 'SEND',
    accountSettingDropDown: "WHAT'S THIS ABOUT?",
    message: 'MESSAGE',
    approval: 'APPROVALS',
    chat: 'CHAT',
    canceled: 'CANCELED',
    orderCardTitle: 'YOUR ACTIVE AND PAST ORDER LIVE HERE!',
    profile: 'VIEW PROFILE',
    offline: 'Offline',
    online: 'Online',
    onFound: 'No Data Found!',
    allCategories : 'All Categories',
    searchResult: 'SEARCH RESULTS',

    //Buttons Strings
    login: 'LOGIN',
    createAccount: 'CREATE ACCOUNT',
    signUpButtonText: 'SIGN UP',
    signInButtonText: 'SIGN IN',
    submit: 'SUBMIT',
    pricing: 'CONTINUE TO PRICING',
    addservice: 'Add Service',
    continueOrder: 'Continue Ordering',
    continueButtonText: 'CONTINUE',
    submitOrder: 'SUBMIT ORDER',
    veriyCode: 'VERIFY CODE',

    //Inputs Strings
    emailText: 'EMAIL',
    passwordText: 'PASSWORD',
    confirmPasswordText: 'CONFIRM PASSWORD',
    mobileNumberText: 'MOBILE NUMBER',
    passwordFourDigitsText: '4-DIGIT PASSWORD',

    //Intro Slides Strings
    firstSlideTitle: 'WANT TO COMPLETE YOUT HOME TASKS!',
    firstSlideDescription: 'CHOOSE FROM OVER 50 HOME SERVICES AT BEST PRICES',
    secondSlideTitle: 'RELAX AND GET YOUR TASKS DONE!',
    secondSlideDescription: 'AND ENJOY YOUR TIME TO DO WHAT YOU LOVE',
    thirdSlideTitle: 'ENJOY WARRANTY  ON SERVICES',
    thirdSlideDescription: 'UPTO 30 DAYS',
    fourthSlideTitle: 'COMPARE SERVICE PROFESSIONALS & CHOOSE',
    fourthSlideDescription: 'THE MOST SUITABLE ONE FOR YOU, CONNECT VIA CHAT OR CALL',

    //SignIn Strings
    signInText: "Don't have any account? ",

    //Login Strings
    signUpText: 'Already have an account? ',
    registerIndividual: 'Register as Individual Expert',
    registerOnline: 'Register your Online Shop',
    privacyPolicy: 'By Signing up, you agreed with our Terms of Services and Privacy Policy',

    //personal information
    personalInfoText: ' PERSONAL INFORMATION',
    fullNameText: 'FULL NAME',
    firstName: 'FIRST NAME',
    lastName: 'LAST NAME',
    phoneNumberText: 'PHONE NUMBER',
    emailAddressText: 'EMAIL ADDRESS',
    address: 'ADDRESS',
    countryText: 'COUNTRY',
    cityText: 'CITY',
    townText: 'TOWN',
    // govIdNumber : 'GOV ID NUMBER',
    uploadGovIdText: 'ID CARD NUMBER',
    govIdText: 'UPLOAD NIC/DRIVING LICENSE',
    uplaodIdCardText: 'UPLOAD ID CARD NUMBER',
    idCardNumberText: 'ID CARD NUMBER',
    qualificationInfoText: 'QUALIFICATION INFORMATION',
    // educationText: 'EDUCATION (DIPLOMA, UNIVERSITY..ETC)',
    // specialityText: 'EDUCATION SPECIALITY',
    experienceText: 'YEARS OF EXPERIENCE',
    bereifYourselfText: 'BEREIF DESCRIPTION ABOUT YOURSELF AND YOUR WORK',
    certificationText: 'CERTIFICATION',
    fileText: 'ATTACH FILE...',
    serviceInfoText: 'SERVICE INFORMATION',
    selectServiceText: 'SELECT SERVICE',
    selectSeviceProvider: 'SELECT SERVICE PROVIDER',

    //Home Strings
    homeTitle: 'HOW CAN WE SERVE YOU?',
    categories: 'Browse Categories',
    seeAll: 'SEE ALL',
    homeInput: 'WHAT ARE YOU LOOKING FOR?',

    //subCategory strings
    subCategoryHeading: 'Choose the type of service',

    //orderGuarantee string
    guaranteeText: 'WE GUARANTEE',
    warrantyServiceText: 'WARRANTY ON SERVICE',
    customerSatisfaction: 'CUSTOMER SATISFACTION',
    customerCenter: 'CUSTOMER HAPPINESS CENTER',
    verified: 'VERIFIED SERVICE PROVIDER',
    promoText: 'DO YOU HAVE A PROMO CODE?',
    promoCode: 'PROMO CODE',
    useCode: 'USE CODE',

    //orderCart String
    orderCartDescription: 'Approximate prices are based on your selected location: Pakistan - Karachi',
    bigShell: 'Big Shell or Painting or Mirror installation',
    startingFrom: 'Starting from',
    perUnit: 'RS per unit',
    youSave: 'You save',
    numberUnit: 'Number of units',
    bigOffer: 'Big Offer',
    price: 'Price',
    totalEstimate: 'Total Estimate',
    totalEstimatePrice: ' PKR + Other prices upon visit',

    //Location Strings
    locationTitle: 'CONFIRM VISIT LOCATION',
    place: 'BUILDING OR APARTMENT  #',

    //schedule STRINGS
    scheduleTitle: 'SELECT PREFERRED VISIT TIME',
    today: 'TODAY',
    tomorrow: 'TOMORROW',

    //serviceProvider String
    serviceProviderTitle: 'SELECT SERVICE PROVIDER',

    //orderSummary strings
    orderSummary: 'ORDER SUMMARY',
    paymentMethod: 'Payment Method',
    initialInvoice: 'Initial Invoice',
    serviceCharge: 'Total Service Charge',
    minimumCharge: 'Provider minimum charge',

    //order sucess string
    successTitle: 'Thank You!',
    successDescription: 'Relax! We have successfully received your order and the service provider will call you soon to follow-up with your request.',
    expectedTime: 'Expected visit time:',

    //Feedback Component
    keepOrder: 'Keep the order',
    question: 'Why would you like to cancel the order?',
    reason: 'Choose a reason to help us improve',
    cancelOrder: 'Cancel the order',
    ansTryApp: 'Try the app',
    ansOrderLater: 'Will Order Later',
    ansServiceProvider: 'Service Provider price is expensive',
    ansNotContacted: 'The service provider has not contacted me yet',
    ansVisitTime: "Visit time is too far I can't wait",
    ansNotSuitable: 'Service provider not suitable for me',
    ansChangeVisit: 'Service provider change visit time',
    ansOther: 'Other',
    inbox: 'INBOX',
    sendText: 'Type your message...',
    labelInbox: 'INBOX',
    labelArchive: 'ARCHIVE',
    labelSpam: 'SPAM',
    labelDeleted: 'DELETED',
    labelLatest: 'LATEST',
    labelRead: 'READ',
    labelUnread: 'UNREAD',
    labelFav: 'FAVOURITE',
    noNotification: 'NO NEW NOTIFICATIONS!',
    notificationLabel: 'Notifications',
    registerProvider: 'Register as Provider',
    resolved: 'RESOLVED',
    appointments: 'NEW APPOINTMENTS',

    //Bottom Bar Strings
    home: 'Home',
    orders: 'Orders',
    msg: 'Messages',
    appro : 'Approvals'
  },

  ur: {
    //common Strings
    sideBarMain: 'مرکزی',
    from: 'سے',
    to: 'تک',
    done: 'مکمل',
    Skip: 'چھوڑ دو',
    next: 'اگلے',
    cash: 'نقد',
    online: 'آن لائن',
    loginForOrder: 'اپنے آرڈر کو جاری رکھنے کے لئے لاگ ان کریں',
    verificationTitle: 'براہ کرم اندراج کی تصدیق کوڈ کریں',
    verificationNumber: 'توثیقی کوڈ بھیجیں',
    verificationCode: 'توثیقی کوڈ',
    codeResend: 'سیکنڈ میں کوڈ دوبارہ بھیجیں',
    loginSuccessText: 'کامیابی کے ساتھ لاگ ان کریں ، براہ کرم آپ کا آرڈر مکمل کریں',
    cancel: 'منسوخ کریں',
    mainPage: 'سرورق',
    orderHistory: 'آرڈر کی تاریخ',
    accountSetting: 'اکاؤنٹ کی ترتیب',
    accountSetting2: 'اکاؤنٹ کی ترتیب',
    registerAsProvider: 'فراہم کنندہ کے طور پر رجسٹر',
    faqText: 'عمومی سوالنامہ',
    aboutUs: 'ہمارے بارے میں',
    signOut: 'باہر جائیں',
    shareApp: 'اے پی پی کا اشتراک کریں',
    myOrder: 'میرے احکام',
    save: 'محفوظ کریں',
    aboutUsText: 'یہ ایک طویل عرصے سے قائم حقیقت ہے کہ پڑھنے والے کے صفحے کی ترتیب کو دیکھتے وقت پڑھنے کے قابل مواد سے انحراف ہوجائے گا۔ لوریم ایپسم کے استعمال کی بات یہ ہے کہ اس میں حرفوں کی کم یا زیادہ عام تقسیم ہوتی ہے ، جیسا کہ یہاں مواد ، یہاں کا مواد استعمال کرنے کے برخلاف ہوتا ہے ، جس سے یہ پڑھنے کے قابل انگریزی لگتا ہے۔',
    text: 'بیک ایپلی کیشن کا استعمال کیوں؟',
    weakPassword: 'کمزور پاس ورڈ',
    strongPasssword: 'مضبوط پاس ورڈ',
    send: 'بھیجیں',
    accountSettingDropDown: 'اس کے بارے میں کیا ہے؟',
    message: 'پیغام',
    canceled: 'منسوخ',
    orderCardTitle: 'آپ کی سرگرمی اور گذشتہ آرڈر یہاں زندہ رہو!',
    profile: 'پروفائل کا مشاھدہ کریں',
    offline: 'آف لائن',
    online: 'آن لائن',
    onFound: 'کوئی ڈیٹا نہیں ملا!',
    allCategories: 'تمام زمرے',
    searchResult: 'تلاش کے نتائج',

    //Button Stringd
    login: 'لاگ ان کریں',
    createAccount: 'اکاؤنٹ بنائیں',
    signUpButtonText: 'سائن اپ',
    signInButtonText: 'سائن ان',
    submit: 'جمع کرائیں',
    pricing: 'قیمتوں کا تعین جاری رکھیں',
    addservice: 'سروس شامل کریں',
    continueOrder: 'آرڈر جاری رکھیں',
    continueButtonText: 'جاری رہے',
    submitOrder: 'آرڈر جمع کرانے',
    veriyCode: 'وریا کوڈ',
    chat: 'چیٹ',
    approval: 'منظوری',

    //Input Strings
    emailText: 'ای میل',
    passwordText: 'پاس ورڈ',
    confirmPasswordText: 'تصدیق پاسورڈ',
    mobileNumberText: 'موبائل فون کانمبر',
    passwordFourDigitsText: 'چار ہندسوں کا پاس ورڈ',

    //Bottom Bar Strings
    home: 'گھر',
    orders: 'احکامات',
    msg: 'پیغامات',
    appro : 'منظوری',

    //Intro Slides Strings
    firstSlideTitle: 'ہوم ٹاسکس کو مکمل کرنا چاہتے ہیں!',
    firstSlideDescription: 'بہترین قیمتوں میں 50 ہوم سروسز سے انتخاب کریں',
    secondSlideTitle: 'آرام کریں اور اپنے کام انجام دیں!',
    secondSlideDescription: 'اور اپنی پسند کی بات کرنے کا لطف اٹھائیں',
    thirdSlideTitle: 'خدمات پر وارنٹی سے لطف اندوز ہوں',
    thirdSlideDescription: ' تک دن 30',
    fourthSlideTitle: 'خدمت پیشہ ور افراد اور انتخاب کا مقابلہ کریں',
    fourthSlideDescription: 'آپ کے لئے سب سے مناسب ، چیٹ یا کال کے ذریعے رابطہ کریں',

    //SignIn Strings
    signInText: 'کوئی اکاؤنٹ نہیں ہے؟',

    //Signup Strings
    signUpText: 'پہلے سے ہی ایک اکاؤنٹ ہے؟',
    registerIndividual: 'انفرادی ماہر کی حیثیت سے رجسٹر ہوں',
    registerOnline: 'اپنی آن لائن شاپ کو رجسٹر کریں',
    privacyPolicy: 'سائن اپ کرکے ، آپ ہماری سروسز کی شرائط اور رازداری کی پالیسی سے اتفاق کرتے ہیں',

    //personal information
    personalInfoText: 'ذاتی معلومات',
    fullNameText: 'پورا نام',
    firstName: 'پہلا نام',
    lastName: 'آخری نام',
    phoneNumberText: 'فون نمبر',
    emailAddressText: 'ای میل اڈریس',
    address: 'اڈریس',
    countryText: 'ملک',
    cityText: 'شہر',
    townText: 'رقبہ',
    // govIdNumber : 'حکومت شناختی نمبر',
    uploadGovIdText: 'شناختی کارڈ نمبر',
    govIdText: 'شناختی کارڈ / ڈرائیونگ لائسنس اپ لوڈ کریں',
    uplaodIdCardText: 'شناختی کارڈ اپ لوڈ کریں',
    idCardNumberText: 'شناختی کارڈ نمبر',
    qualificationInfoText: 'اہلیت کی معلومات',
    // educationText: 'تعلیم (ڈپلوما ، اقوام متحدہ..ٹی سی)',
    // specialityText: 'تعلیم خاص',
    experienceText: 'تجربے کے سال',
    bereifYourselfText: 'اپنی اور اپنے کام کے بارے میں تفصیل سے تفصیل حاصل کریں',
    certificationText: 'تصدیق',
    fileText: 'فائل منسلک...',
    serviceInfoText: 'سروس کی معلومات',
    selectServiceText: 'خدمت منتخب کریں',
    selectSeviceProvider: 'خدمت فراہم کنندہ منتخب کریں',

    //Home Strings
    homeTitle: 'ہم آپ کی خدمت کیسے کر سکتے ہیں؟',
    categories: 'زمرے براؤز کریں',
    seeAll: 'تمام دیکھیں',
    homeInput: 'آپ کیا تلاش کرنا چاہتے ہیں؟',

    //subCategory strings
    subCategoryHeading: 'خدمت کی قسم منتخب کریں',

    //orderGuarantee string
    guaranteeText: 'ہم ضمانت دیتے ہیں',
    warrantyServiceText: 'سروس پر وارنٹی',
    customerSatisfaction: 'گاہکوں کی اطمینان',
    customerCenter: 'گاہک خوشی کا مرکز',
    verified: 'تصدیق شدہ خدمت فراہم کنندہ',
    promoText: 'کیا آپ کو کوئی پرومو کوڈ ہے؟',
    promoCode: 'پرومو کوڈ',
    useCode: 'کوڈ استعمال کریں',

    //orderCart String
    orderCartDescription: 'لگ بھگ قیمتیں آپ کے منتخب کردہ مقام پر منحصر ہیں: پاکستان کراچی',
    bigShell: 'بگ شیل یا پینٹنگ یا آئر انسٹالیشن',
    startingFrom: 'شروع ہو رہا ہے',
    perUnit: 'فی یونٹ سے',
    youSave: 'بچت',
    numberUnit: 'یونٹوں کی تعداد',
    bigOffer: 'بڑی پیش کش',
    price: 'قیمت',
    totalEstimate: 'کل تخمینہ',
    totalEstimatePrice: 'دورے کے بعد دوسری قیمتیں',

    //Location Strings
    locationTitle: 'تصدیق کا مقام ملاحظہ کریں',
    place: 'بلڈنگ یا اپارٹمنٹ',

    //schedule STRINGS
    scheduleTitle: 'پیش کردہ چھٹے وقت کا انتخاب کریں',
    today: 'آج',
    tomorrow: 'کل',

    //serviceProvider String
    serviceProviderTitle: 'خدمت فراہم کنندہ منتخب کریں',
    paymentMethod: 'ادائیگی کا طریقہ',

    //orderSummary strings
    orderSummary: 'حکم کا خلاصہ',
    initialInvoice: 'ابتدائی رسید',
    serviceCharge: 'کل سروس چارج',
    minimumCharge: 'مہیا کرنے والے کا کم سے کم چارج',

    //order sucess string
    successTitle: 'شکریہ!',
    successDescription: 'آرام کرو! ہمیں کامیابی کے ساتھ آپ کا آرڈر موصول ہوگیا ہے اور خدمت گزار آپ کی درخواست کے تعاقب کے لئے جلد ہی آپ کو کال کرے گا۔',
    expectedTime: ':متوقع وزٹ کا وقت',

    //Feedback Component
    keepOrder: 'حکم جاری رکھیں',
    question: 'آپ آرڈر کیوں منسوخ کرنا چاہیں گے؟',
    reason: 'ہماری بہتری میں مدد کے لئے کوئی وجہ منتخب کریں',
    cancelOrder: 'آرڈر منسوخ کریں',
    ansTryApp: 'ایپ آزمائیں',
    ansOrderLater: 'بعد میں آرڈر کریں گے',
    ansServiceProvider: 'سروس فراہم کرنے والے کی قیمت مہنگی ہے',
    ansNotContacted: 'خدمت فراہم کرنے والے نے مجھ سے ابھی تک رابطہ نہیں کیا ہے',
    ansVisitTime: 'وزٹ کا وقت بہت دور ہے میں انتظار نہیں کرسکتا',
    ansNotSuitable: 'خدمت فراہم کرنے والا میرے لئے موزوں نہیں ہے',
    ansChangeVisit: 'سروس فراہم کرنے والے کا دورے کا وقت تبدیل ہوتا ہے',
    ansOther: 'دیگر',
    inbox: 'ان باکس',
    sendText: 'اپنا پیغام ٹائپ کریں',
    labelInbox: 'ان باکس',
    labelArchive: 'آرکائیو',
    labelSpam: 'فضول',
    labelDeleted: 'حذف ہوگیا',
    labelLatest: 'تازہ ترین',
    labelRead: 'پڑھا ہوا',
    labelUnread: 'پڑھیں',
    labelFav: 'پسندیدہ',
    noNotification: 'کوئی نئی نوٹیفیکیشن نہیں',
    notificationLabel: 'اطلاعات',
    registerProvider: 'فراہم کنندہ کے طور پر رجسٹر',
    resolved: 'حل شدہ',
    appointments: 'نئی تقرریوں'
  }
};

export default Languages;
