require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
permissions_path = '../node_modules/react-native-permissions/ios'

platform :ios, '12.0'

target 'expert4u' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"

  target 'expert4uTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'expert4u-tvOS' do
  # Pods for expert4u-tvOS

  target 'expert4u-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
