export const INTRODUCTION_COMPLETED = 'INTRODUCTION_COMPLETED'
export const INTRODUCTION_COMPLETED_SUCCESS = 'INTRODUCTION_COMPLETED_SUCCESS' 
export const INTRODUCTION_COMPLETED_FALURE = 'INTRODUCTION_COMPLETED_FALURE'