export const SUB_SERVICES_DETAILS_START = 'SUB_SERVICES_DETAILS_START'
export const SUB_SERVICES_DETAILS_SUCCESS = 'SUB_SERVICES_DETAILS_SUCCESS'
export const SUB_SERVICES_DETAILS_FAILURE = 'SUB_SERVICES_DETAILS_FAILURE'